# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Tran Rémi - developer

# Short description (goes below the title; it will also be used in the RSS feed)
description: I help businesses, organisations and individuals from around the world to design & build memorable, hype interfaces and define seamless & meaningful experiences.

# Your name, as you want it to appear underneath each post and in the footer
author: Tran Rémi

# Your email if you want it to be linked on the contact page
author_email: tranremi@live.fr


# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://trinketmage.github.io/
